import { Locale, WorkExperienceType } from "@/types";

export const workExperience: Locale<WorkExperienceType> = {
	en: [
		{
			date_start: new Date("2024-02-01"),
			date_end: new Date("2025-11-01"),
			company: "Masterskaya",
			role: "Frontend Developer",
			location: "Remote",
			description: [
				"As part of an outsourcing team, developed a web application for finding service professionals (similar to Profi.ru) using Next.js and RTK",
				"Acted as a frontend team lead: coordinated the team, distributed tasks, collaborated with the client and designer, and contributed to architectural decisions",
				"Initiated migration from React to Next.js, improving performance, SEO, and overall application architecture",
				"Migrated API layer from createAsyncThunk to RTK Query, reducing boilerplate and speeding up feature development",
				"Designed and implemented a real-time chat (WebSocket) with support for messages, images, and files, as well as an order lifecycle management system",
				"Optimized performance by eliminating unnecessary re-renders, reducing bundle size, and improving data loading speed",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
				{ label: "RTK Query", href: "https://redux-toolkit.js.org/rtk-query/overview" },
				{ label: "WebSocket", href: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API" },
			],
		},
		{
			date_start: new Date("2023-01-01"),
			date_end: new Date("2024-01-30"),
			company: "Freelance",
			role: "Frontend Developer",
			location: "Remote",
			description: [
				"Developed and maintained SPA and SSR applications using React and Next.js, improving page load times by 50%+",
				"Configured and optimized Webpack builds, reducing bundle size by ~20–40% using code splitting and tree shaking",
				"Built pixel-perfect interfaces from Figma and developed UI kits, accelerating feature delivery by 20–30%",
				"Integrated REST and WebSocket APIs, ensuring stable real-time functionality without critical failures",
				"Handled deployment and availability on VDS/VPS (Nginx, SSL), maintaining ~99%+ uptime",
				"Performed refactoring and component decomposition, reducing complexity and speeding up development",
				"Participated in the full development lifecycle, improving time-to-market through accurate estimations",
				"Maintained and improved TypeScript codebases, reducing runtime errors and increasing reliability",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Webpack", href: "https://webpack.js.org/" },
				{ label: "Nginx", href: "https://nginx.org/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
			],
		},
		{
			date_start: new Date("2025-04-01"),
			date_end: new Date("2025-05-30"),
			company: "Sibcode",
			role: "Project Manager Intern",
			location: "Tomsk, Remote",
			description: [
				"Analyzed product structures and formalized requirements through briefs and technical specifications",
				"Modeled business processes and user flows (BPMN), improving product understanding before development",
				"Organized team workflow in Bitrix24: decomposed tasks, set priorities, defined deadlines, and tracked progress using Kanban and Gantt charts",
				"Designed UX/UI solutions: created interface prototypes in Figma based on user scenarios",
				"Conducted functional testing, identifying critical bugs before release and reducing production issues",
			],
			tags: [
				{ label: "Sibcode", href: "https://sibcode.team/" },
				{ label: "Figma", href: "https://www.figma.com/" },
				{ label: "Miro", href: "https://miro.com/" },
				{ label: "Bitrix24", href: "https://www.bitrix24.com/" },
			],
		},
	],
	ru: [
		{
			date_start: new Date("2024-02-01"),
			date_end: new Date("2025-11-01"),
			company: "Мастерская",
			role: "Frontend-разработчик",
			location: "Удаленная",
			description: [
				"В составе аутсорс-команды разрабатывал веб-приложение для поиска мастеров (аналог Profi.ru) с использованием Next.js и RTK",
				"Выступал лидом фронтенд-разработки: координировал команду, распределял задачи, выстраивал взаимодействие с заказчиком и дизайнером, участвовал в принятии архитектурных решений",
				"Инициировал миграцию с React на Next.js, улучшив производительность, SEO и архитектуру приложения",
				"Перевёл работу с API с createAsyncThunk на RTK Query, сократив объём шаблонного кода и ускорив разработку новых фич",
				"Спроектировал и реализовал real-time чат (WebSocket) с поддержкой сообщений, изображений и файлов, а также систему управления жизненным циклом заказа",
				"Оптимизировал производительность: устранил избыточные ререндеры, уменьшил размер бандла и ускорил загрузку данных, повысив отзывчивость интерфейса",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
				{ label: "RTK Query", href: "https://redux-toolkit.js.org/rtk-query/overview" },
				{ label: "WebSocket", href: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API" },
			],
		},
		{
			date_start: new Date("2023-01-01"),
			date_end: new Date("2024-01-30"),
			company: "Работа на себя",
			role: "Frontend-разработчик",
			location: "Удаленная",
			description: [
				"Разрабатывал и поддерживал SPA и SSR-приложения на React и Next.js, обеспечивая стабильную работу и сокращение времени загрузки страниц на 50%+",
				"Отвечал за настройку и оптимизацию сборки Webpack, сокращая размер бандла на ~20–40% за счёт code splitting и tree shaking",
				"Реализовывал pixel-perfect интерфейсы по Figma и развивал UI-киты, ускоряя разработку новых экранов и фич на 20–30%",
				"Интегрировал REST и WebSocket API, обеспечивая стабильную работу real-time функциональности без критических сбоев",
				"Отвечал за деплой и доступность приложений на VDS/VPS (Nginx, SSL), обеспечивая uptime на уровне ~99%+",
				"Проводил рефакторинг и декомпозицию, снижая сложность компонентов и ускоряя разработку новых фич",
				"Участвовал во всём жизненном цикле разработки, сокращая time-to-market фич за счёт более точной технической оценки",
				"Поддерживал и развивал TypeScript-кодовые базы, снижая количество runtime-ошибок и повышая надёжность приложений",
			],
			tags: [
				{ label: "Nextjs", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Webpack", href: "https://webpack.js.org/" },
				{ label: "Nginx", href: "https://nginx.org/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
			],
		},
		{
			date_start: new Date("2025-04-01"),
			date_end: new Date("2025-05-30"),
			company: "Sibcode",
			role: "Менеджер проекта (стажер)",
			location: "Томск, удаленная",
			description: [
				"Анализировал структуру продуктов и формализовывал требования через брифы и технические задания",
				"Моделировал бизнес-процессы и пользовательские сценарии (BPMN), улучшая понимание логики продукта перед разработкой",
				"Организовывал командную работу в Bitrix24: декомпозировал задачи, определял приоритеты, устанавливал сроки и контролировал выполнение через Kanban и диаграмму Ганта",
				"Прорабатывал UX/UI решений: создавал прототипы интерфейсов в Figma с учётом пользовательских сценариев",
				"Проводил функциональное тестирование, выявляя критические баги до релиза и снижая количество ошибок в продакшене",
			],
			tags: [
				{ label: "Sibcode", href: "https://sibcode.team/" },
				{ label: "Figma", href: "https://www.figma.com/" },
				{ label: "Miro", href: "https://miro.com/" },
				{ label: "bitrix24", href: "https://www.bitrix24.ru/" },
			],
		},
	],
	de: [
		{
			date_start: new Date("2024-02-01"),
			date_end: new Date("2025-11-01"),
			company: "Masterskaya",
			role: "Frontend-Entwickler",
			location: "Remote",
			description: [
				"Als Teil eines Outsourcing-Teams entwickelte ich eine Webanwendung zur Suche nach Dienstleistern (ähnlich wie Profi.ru) mit Next.js und RTK",
				"Übernahm die Rolle des Frontend-Teamleiters: koordinierte das Team, verteilte Aufgaben, arbeitete mit Kunden und Designern zusammen und beteiligte mich an Architekturentscheidungen",
				"Initiierte die Migration von React zu Next.js und verbesserte dadurch Performance, SEO und die Gesamtarchitektur der Anwendung",
				"Stellte die API-Anbindung von createAsyncThunk auf RTK Query um, reduzierte Boilerplate-Code und beschleunigte die Entwicklung neuer Features",
				"Konzipierte und implementierte einen Real-Time-Chat (WebSocket) mit Unterstützung für Nachrichten, Bilder und Dateien sowie ein System zur Verwaltung des Auftragslebenszyklus",
				"Optimierte die Performance durch Reduzierung unnötiger Re-Renders, Verkleinerung des Bundles und schnellere Datenladezeiten",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
				{ label: "RTK Query", href: "https://redux-toolkit.js.org/rtk-query/overview" },
				{ label: "WebSocket", href: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API" },
			],
		},
		{
			date_start: new Date("2023-01-01"),
			date_end: new Date("2024-01-30"),
			company: "Freelance",
			role: "Frontend-Entwickler",
			location: "Remote",
			description: [
				"Entwickelte und wartete SPA- und SSR-Anwendungen mit React und Next.js und reduzierte Ladezeiten um über 50%",
				"Konfigurierte und optimierte Webpack-Builds und reduzierte die Bundle-Größe um ca. 20–40% durch Code Splitting und Tree Shaking",
				"Erstellte pixelgenaue Benutzeroberflächen nach Figma-Designs und entwickelte UI-Kits, wodurch die Feature-Entwicklung um 20–30% beschleunigt wurde",
				"Integrierte REST- und WebSocket-APIs und stellte stabile Real-Time-Funktionalität ohne kritische Ausfälle sicher",
				"Verantwortlich für Deployment und Verfügbarkeit auf VDS/VPS (Nginx, SSL) mit einer Uptime von ~99%+",
				"Führte Refactoring und Komponenten-Dekomposition durch, reduzierte Komplexität und beschleunigte die Entwicklung",
				"War am gesamten Entwicklungszyklus beteiligt und verkürzte die Time-to-Market durch genauere Aufwandsabschätzung",
				"Pflegte und entwickelte TypeScript-Codebasen weiter und reduzierte Runtime-Fehler",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Webpack", href: "https://webpack.js.org/" },
				{ label: "Nginx", href: "https://nginx.org/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
			],
		},
		{
			date_start: new Date("2025-04-01"),
			date_end: new Date("2025-05-30"),
			company: "Sibcode",
			role: "Praktikant Projektmanager",
			location: "Tomsk, Remote",
			description: [
				"Analysierte Produktstrukturen und formulierte Anforderungen in Form von Briefings und technischen Spezifikationen",
				"Modellierte Geschäftsprozesse und User Flows (BPMN) zur besseren Vorbereitung der Entwicklung",
				"Organisierte Teamarbeit in Bitrix24: zerlegte Aufgaben, setzte Prioritäten, definierte Deadlines und verfolgte Fortschritte über Kanban und Gantt-Diagramme",
				"Erarbeitete UX/UI-Lösungen und erstellte Prototypen in Figma basierend auf Nutzer-Szenarien",
				"Führte funktionale Tests durch, identifizierte kritische Bugs vor dem Release und reduzierte Produktionsfehler",
			],
			tags: [
				{ label: "Sibcode", href: "https://sibcode.team/" },
				{ label: "Figma", href: "https://www.figma.com/" },
				{ label: "Miro", href: "https://miro.com/" },
				{ label: "Bitrix24", href: "https://www.bitrix24.com/" },
			],
		},
	],
	fi: [
		{
			date_start: new Date("2024-02-01"),
			date_end: new Date("2025-11-01"),
			company: "Masterskaya",
			role: "Frontend-kehittäjä",
			location: "Etätyö",
			description: [
				"Osana ulkoistettua tiimiä kehitin verkkosovellusta palveluntarjoajien etsimiseen (Profi.ru:n kaltainen) käyttäen Next.js:ää ja RTK:ta",
				"Toimin frontend-tiimin vetäjänä: koordinoin tiimiä, jaoin tehtäviä, tein yhteistyötä asiakkaan ja suunnittelijan kanssa sekä osallistuin arkkitehtuuripäätöksiin",
				"Aloitin migraation Reactista Next.js:ään, mikä paransi suorituskykyä, SEO:ta ja sovelluksen arkkitehtuuria",
				"Siirsin API-kerroksen createAsyncThunkista RTK Queryyn, vähensin boilerplate-koodia ja nopeutin uusien ominaisuuksien kehitystä",
				"Suunnittelin ja toteutin reaaliaikaisen chatin (WebSocket), joka tukee viestejä, kuvia ja tiedostoja sekä tilausten elinkaaren hallintaa",
				"Optimoin suorituskykyä poistamalla turhia uudelleenrenderöintejä, pienentämällä bundle-kokoa ja nopeuttamalla datan latausta",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
				{ label: "RTK Query", href: "https://redux-toolkit.js.org/rtk-query/overview" },
				{ label: "WebSocket", href: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API" },
			],
		},
		{
			date_start: new Date("2023-01-01"),
			date_end: new Date("2024-01-30"),
			company: "Freelance",
			role: "Frontend-kehittäjä",
			location: "Etätyö",
			description: [
				"Kehitin ja ylläpidin SPA- ja SSR-sovelluksia Reactilla ja Next.js:llä, parantaen latausaikoja yli 50%",
				"Konfiguroin ja optimoin Webpack-buildit, pienensin bundle-kokoa noin 20–40% code splittingin ja tree shakingin avulla",
				"Toteutin pixel-perfect käyttöliittymiä Figma-suunnitelmien pohjalta ja kehitin UI-kirjastoja, nopeuttaen kehitystä 20–30%",
				"Integroin REST- ja WebSocket-rajapintoja varmistaen vakaan reaaliaikaisen toiminnallisuuden",
				"Vastasin sovellusten deploysta ja saatavuudesta VDS/VPS-ympäristöissä (Nginx, SSL), ylläpitäen ~99% käyttöastetta",
				"Suoritin refaktorointia ja komponenttien pilkkomista, vähentäen monimutkaisuutta ja nopeuttaen kehitystä",
				"Osallistuin koko kehitysprosessiin, parantaen time-to-marketia tarkemman arvioinnin avulla",
				"Ylläpidin ja kehitin TypeScript-koodikantaa, vähentäen runtime-virheitä ja parantaen luotettavuutta",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Webpack", href: "https://webpack.js.org/" },
				{ label: "Nginx", href: "https://nginx.org/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
			],
		},
		{
			date_start: new Date("2025-04-01"),
			date_end: new Date("2025-05-30"),
			company: "Sibcode",
			role: "Projektipäällikköharjoittelija",
			location: "Tomsk, Etätyö",
			description: [
				"Analysoin tuotteiden rakennetta ja määrittelin vaatimuksia briiffien ja teknisten spesifikaatioiden avulla",
				"Mallinsin liiketoimintaprosesseja ja käyttäjäpolkuja (BPMN) parantaen ymmärrystä ennen kehitystä",
				"Organisoin tiimityötä Bitrix24:ssä: pilkoin tehtäviä, määritin prioriteetit, aikataulut ja seurasin edistymistä Kanbanin ja Gantt-kaavioiden avulla",
				"Suunnittelin UX/UI-ratkaisuja ja loin prototyyppejä Figmassa käyttäjäpolkujen pohjalta",
				"Suoritin funktionaalista testausta, löysin kriittisiä bugeja ennen julkaisua ja vähensin tuotantovirheitä",
			],
			tags: [
				{ label: "Sibcode", href: "https://sibcode.team/" },
				{ label: "Figma", href: "https://www.figma.com/" },
				{ label: "Miro", href: "https://miro.com/" },
				{ label: "Bitrix24", href: "https://www.bitrix24.com/" },
			],
		},
	],
	zh: [
		{
			date_start: new Date("2024-02-01"),
			date_end: new Date("2025-11-01"),
			company: "Masterskaya",
			role: "前端开发工程师",
			location: "远程",
			description: [
				"作为外包团队成员，使用 Next.js 和 RTK 开发了一个服务人员搜索平台（类似 Profi.ru）",
				"担任前端负责人：协调团队、分配任务，与客户和设计师沟通，并参与架构决策",
				"推动从 React 向 Next.js 迁移，提升了性能、SEO 以及整体架构",
				"将 API 层从 createAsyncThunk 迁移到 RTK Query，减少模板代码并加快功能开发速度",
				"设计并实现了实时聊天功能（WebSocket），支持消息、图片和文件，以及订单生命周期管理系统",
				"优化应用性能：减少不必要的重复渲染、降低包体积并提升数据加载速度，提高了整体响应性",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
				{ label: "RTK Query", href: "https://redux-toolkit.js.org/rtk-query/overview" },
				{ label: "WebSocket", href: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API" },
			],
		},
		{
			date_start: new Date("2023-01-01"),
			date_end: new Date("2024-01-30"),
			company: "自由职业",
			role: "前端开发工程师",
			location: "远程",
			description: [
				"使用 React 和 Next.js 开发和维护 SPA 与 SSR 应用，将页面加载时间缩短 50% 以上",
				"配置并优化 Webpack 构建，通过代码分割和 tree shaking 将包体积减少约 20–40%",
				"根据 Figma 设计实现像素级还原界面，并构建 UI 组件库，提高开发效率 20–30%",
				"集成 REST 和 WebSocket API，确保实时功能稳定运行",
				"负责在 VDS/VPS（Nginx、SSL）上的部署与可用性，保持约 99% 以上的稳定性",
				"进行代码重构与组件拆分，降低复杂度并提升开发效率",
				"参与完整开发生命周期，通过更准确的评估缩短功能上线时间",
				"维护和优化 TypeScript 代码库，减少运行时错误并提升系统可靠性",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Webpack", href: "https://webpack.js.org/" },
				{ label: "Nginx", href: "https://nginx.org/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
			],
		},
		{
			date_start: new Date("2025-04-01"),
			date_end: new Date("2025-05-30"),
			company: "Sibcode",
			role: "项目经理实习生",
			location: "托木斯克，远程",
			description: [
				"分析产品结构，并通过需求文档和技术说明书梳理需求",
				"建模业务流程和用户路径（BPMN），提升开发前对产品逻辑的理解",
				"在 Bitrix24 中组织团队工作：拆分任务、设定优先级和截止时间，并通过看板和甘特图跟踪进度",
				"参与 UX/UI 设计，在 Figma 中根据用户场景制作原型",
				"执行功能测试，在上线前发现关键问题，减少生产环境中的错误",
			],
			tags: [
				{ label: "Sibcode", href: "https://sibcode.team/" },
				{ label: "Figma", href: "https://www.figma.com/" },
				{ label: "Miro", href: "https://miro.com/" },
				{ label: "Bitrix24", href: "https://www.bitrix24.com/" },
			],
		},
	],
	es: [
		{
			date_start: new Date("2024-02-01"),
			date_end: new Date("2025-11-01"),
			company: "Masterskaya",
			role: "Desarrollador Frontend",
			location: "Remoto",
			description: [
				"Como parte de un equipo de outsourcing, desarrollé una aplicación web para la búsqueda de profesionales (similar a Profi.ru) utilizando Next.js y RTK",
				"Actué como líder de frontend: coordiné el equipo, distribuí tareas, colaboré con el cliente y el diseñador, y participé en decisiones de arquitectura",
				"Impulsé la migración de React a Next.js, mejorando el rendimiento, el SEO y la arquitectura general de la aplicación",
				"Migré la capa de API de createAsyncThunk a RTK Query, reduciendo código repetitivo y acelerando el desarrollo de nuevas funcionalidades",
				"Diseñé e implementé un chat en tiempo real (WebSocket) con soporte para mensajes, imágenes y archivos, así como un sistema de gestión del ciclo de vida de pedidos",
				"Optimicé el rendimiento eliminando renderizados innecesarios, reduciendo el tamaño del bundle y mejorando la carga de datos",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
				{ label: "RTK Query", href: "https://redux-toolkit.js.org/rtk-query/overview" },
				{ label: "WebSocket", href: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API" },
			],
		},
		{
			date_start: new Date("2023-01-01"),
			date_end: new Date("2024-01-30"),
			company: "Freelance",
			role: "Desarrollador Frontend",
			location: "Remoto",
			description: [
				"Desarrollé y mantuve aplicaciones SPA y SSR con React y Next.js, reduciendo los tiempos de carga en más de un 50%",
				"Configuré y optimicé builds de Webpack, reduciendo el tamaño del bundle en aproximadamente 20–40% mediante code splitting y tree shaking",
				"Implementé interfaces pixel-perfect basadas en Figma y desarrollé UI kits, acelerando el desarrollo en un 20–30%",
				"Integré APIs REST y WebSocket, asegurando una funcionalidad en tiempo real estable",
				"Gestioné el despliegue y la disponibilidad en VDS/VPS (Nginx, SSL), manteniendo un uptime de ~99%+",
				"Realicé refactorización y descomposición de componentes, reduciendo la complejidad y mejorando la velocidad de desarrollo",
				"Participé en todo el ciclo de desarrollo, mejorando el time-to-market mediante estimaciones más precisas",
				"Mantuve y mejoré bases de código en TypeScript, reduciendo errores en tiempo de ejecución",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Webpack", href: "https://webpack.js.org/" },
				{ label: "Nginx", href: "https://nginx.org/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
			],
		},
		{
			date_start: new Date("2025-04-01"),
			date_end: new Date("2025-05-30"),
			company: "Sibcode",
			role: "Practicante de Project Manager",
			location: "Tomsk, Remoto",
			description: [
				"Analicé la estructura de productos y formalicé requisitos mediante briefs y especificaciones técnicas",
				"Modelé procesos de negocio y flujos de usuario (BPMN), mejorando la comprensión del producto antes del desarrollo",
				"Organicé el trabajo del equipo en Bitrix24: descompuse tareas, definí prioridades y plazos, y realicé seguimiento con Kanban y diagramas de Gantt",
				"Diseñé soluciones UX/UI y creé prototipos en Figma basados en escenarios de usuario",
				"Realicé pruebas funcionales, detectando errores críticos antes del lanzamiento y reduciendo incidencias en producción",
			],
			tags: [
				{ label: "Sibcode", href: "https://sibcode.team/" },
				{ label: "Figma", href: "https://www.figma.com/" },
				{ label: "Miro", href: "https://miro.com/" },
				{ label: "Bitrix24", href: "https://www.bitrix24.com/" },
			],
		},
	],
	fr: [
		{
			date_start: new Date("2024-02-01"),
			date_end: new Date("2025-11-01"),
			company: "Masterskaya",
			role: "Développeur Frontend",
			location: "À distance",
			description: [
				"Au sein d’une équipe d’externalisation, j’ai développé une application web de mise en relation avec des prestataires (similaire à Profi.ru) avec Next.js et RTK",
				"J’ai occupé le rôle de lead frontend : coordination de l’équipe, répartition des tâches, collaboration avec le client et le designer, participation aux décisions d’architecture",
				"J’ai initié la migration de React vers Next.js, améliorant les performances, le SEO et l’architecture globale",
				"J’ai migré la couche API de createAsyncThunk vers RTK Query, réduisant le code répétitif et accélérant le développement des fonctionnalités",
				"J’ai conçu et implémenté un chat en temps réel (WebSocket) avec support des messages, images et fichiers, ainsi qu’un système de gestion du cycle de vie des commandes",
				"J’ai optimisé les performances en supprimant les re-renders inutiles, en réduisant la taille du bundle et en améliorant le chargement des données",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
				{ label: "RTK Query", href: "https://redux-toolkit.js.org/rtk-query/overview" },
				{ label: "WebSocket", href: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API" },
			],
		},
		{
			date_start: new Date("2023-01-01"),
			date_end: new Date("2024-01-30"),
			company: "Freelance",
			role: "Développeur Frontend",
			location: "À distance",
			description: [
				"Développement et maintenance d’applications SPA et SSR avec React et Next.js, réduisant les temps de chargement de plus de 50%",
				"Configuration et optimisation des builds Webpack, réduisant la taille du bundle d’environ 20 à 40% grâce au code splitting et au tree shaking",
				"Implémentation d’interfaces pixel-perfect à partir de Figma et développement de UI kits, accélérant la création de nouvelles fonctionnalités de 20 à 30%",
				"Intégration d’APIs REST et WebSocket, assurant une fonctionnalité temps réel stable",
				"Gestion du déploiement et de la disponibilité sur VDS/VPS (Nginx, SSL), avec un uptime d’environ 99%+",
				"Refactoring et décomposition des composants, réduisant la complexité et accélérant le développement",
				"Participation à l’ensemble du cycle de développement, améliorant le time-to-market grâce à de meilleures estimations",
				"Maintenance et amélioration de bases de code TypeScript, réduisant les erreurs à l’exécution",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Webpack", href: "https://webpack.js.org/" },
				{ label: "Nginx", href: "https://nginx.org/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
			],
		},
		{
			date_start: new Date("2025-04-01"),
			date_end: new Date("2025-05-30"),
			company: "Sibcode",
			role: "Stagiaire Chef de projet",
			location: "Tomsk, À distance",
			description: [
				"Analyse de la structure des produits et formalisation des exigences via des briefs et des spécifications techniques",
				"Modélisation des processus métier et des parcours utilisateurs (BPMN), améliorant la compréhension du produit avant le développement",
				"Organisation du travail d’équipe dans Bitrix24 : découpage des tâches, définition des priorités et des délais, suivi via Kanban et diagrammes de Gantt",
				"Conception de solutions UX/UI et création de prototypes dans Figma basés sur les scénarios utilisateurs",
				"Réalisation de tests fonctionnels, identification de bugs critiques avant la mise en production et réduction des incidents",
			],
			tags: [
				{ label: "Sibcode", href: "https://sibcode.team/" },
				{ label: "Figma", href: "https://www.figma.com/" },
				{ label: "Miro", href: "https://miro.com/" },
				{ label: "Bitrix24", href: "https://www.bitrix24.com/" },
			],
		},
	],
	ar: [
		{
			date_start: new Date("2024-02-01"),
			date_end: new Date("2025-11-01"),
			company: "Masterskaya",
			role: "مطور واجهات أمامية",
			location: "عن بُعد",
			description: [
				"كجزء من فريق خارجي، قمت بتطوير تطبيق ويب للبحث عن مقدمي الخدمات (مشابه لـ Profi.ru) باستخدام Next.js و RTK",
				"عملت كقائد لفريق الواجهة الأمامية: تنسيق الفريق، توزيع المهام، التعاون مع العميل والمصمم، والمشاركة في اتخاذ القرارات المعمارية",
				"بادرت بعملية الانتقال من React إلى Next.js، مما أدى إلى تحسين الأداء وSEO وبنية التطبيق",
				"قمت بترحيل طبقة API من createAsyncThunk إلى RTK Query، مما قلل من الشيفرة المتكررة وسرّع تطوير الميزات",
				"صممت ونفذت نظام دردشة فورية (WebSocket) يدعم الرسائل والصور والملفات، بالإضافة إلى نظام إدارة دورة حياة الطلبات",
				"حسّنت الأداء من خلال تقليل عمليات إعادة التصيير غير الضرورية، وتقليل حجم الحزمة، وتسريع تحميل البيانات",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
				{ label: "RTK Query", href: "https://redux-toolkit.js.org/rtk-query/overview" },
				{ label: "WebSocket", href: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API" },
			],
		},
		{
			date_start: new Date("2023-01-01"),
			date_end: new Date("2024-01-30"),
			company: "عمل حر",
			role: "مطور واجهات أمامية",
			location: "عن بُعد",
			description: [
				"طورت وصنت تطبيقات SPA وSSR باستخدام React وNext.js، مما أدى إلى تقليل زمن تحميل الصفحات بأكثر من 50%",
				"قمت بإعداد وتحسين Webpack، مما قلل حجم الحزمة بنسبة تقريبية 20–40% باستخدام code splitting وtree shaking",
				"نفذت واجهات دقيقة وفق تصميمات Figma وطورت مكتبات UI، مما سرّع تطوير الميزات بنسبة 20–30%",
				"قمت بدمج REST وWebSocket APIs، مما ضمن استقرار الوظائف اللحظية دون أخطاء حرجة",
				"توليت نشر التطبيقات وضمان توفرها على VDS/VPS (Nginx، SSL) مع uptime يقارب 99%+",
				"أجريت عمليات refactoring وتقسيم المكونات، مما قلل التعقيد وسرّع عملية التطوير",
				"شاركت في كامل دورة حياة التطوير، مما حسّن time-to-market من خلال تقديرات أدق",
				"حافظت على قواعد كود TypeScript وطورتها، مما قلل من أخطاء وقت التشغيل وزاد من موثوقية التطبيقات",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Webpack", href: "https://webpack.js.org/" },
				{ label: "Nginx", href: "https://nginx.org/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
			],
		},
		{
			date_start: new Date("2025-04-01"),
			date_end: new Date("2025-05-30"),
			company: "Sibcode",
			role: "متدرب مدير مشروع",
			location: "تومسك، عن بُعد",
			description: [
				"قمت بتحليل هيكل المنتجات وصياغة المتطلبات من خلال الوثائق والمواصفات التقنية",
				"نموذجت العمليات التجارية ومسارات المستخدم (BPMN)، مما حسّن فهم المنتج قبل التطوير",
				"نظمت عمل الفريق في Bitrix24: تقسيم المهام، تحديد الأولويات والمواعيد النهائية، ومتابعة التقدم باستخدام Kanban وGantt",
				"شاركت في تصميم UX/UI وأنشأت نماذج أولية في Figma بناءً على سيناريوهات المستخدم",
				"أجريت اختبارات وظيفية، واكتشفت الأخطاء الحرجة قبل الإطلاق، مما قلل من مشاكل الإنتاج",
			],
			tags: [
				{ label: "Sibcode", href: "https://sibcode.team/" },
				{ label: "Figma", href: "https://www.figma.com/" },
				{ label: "Miro", href: "https://miro.com/" },
				{ label: "Bitrix24", href: "https://www.bitrix24.com/" },
			],
		},
	],
	pt: [
		{
			date_start: new Date("2024-02-01"),
			date_end: new Date("2025-11-01"),
			company: "Masterskaya",
			role: "Desenvolvedor Frontend",
			location: "Remoto",
			description: [
				"Como parte de uma equipe de outsourcing, desenvolvi uma aplicação web para busca de prestadores de serviços (semelhante ao Profi.ru) utilizando Next.js e RTK",
				"Atuei como líder de frontend: coordenei a equipe, distribuí tarefas, colaborei com o cliente e o designer e participei de decisões arquiteturais",
				"Iniciei a migração de React para Next.js, melhorando desempenho, SEO e a arquitetura geral da aplicação",
				"Migrei a camada de API de createAsyncThunk para RTK Query, reduzindo código repetitivo e acelerando o desenvolvimento de novas funcionalidades",
				"Projetei e implementei um chat em tempo real (WebSocket) com suporte a mensagens, imagens e arquivos, além de um sistema de gerenciamento do ciclo de vida de pedidos",
				"Otimizei o desempenho eliminando re-renderizações desnecessárias, reduzindo o tamanho do bundle e melhorando o carregamento de dados",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
				{ label: "RTK Query", href: "https://redux-toolkit.js.org/rtk-query/overview" },
				{ label: "WebSocket", href: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API" },
			],
		},
		{
			date_start: new Date("2023-01-01"),
			date_end: new Date("2024-01-30"),
			company: "Freelance",
			role: "Desenvolvedor Frontend",
			location: "Remoto",
			description: [
				"Desenvolvi e mantive aplicações SPA e SSR com React e Next.js, reduzindo o tempo de carregamento em mais de 50%",
				"Configurei e otimizei builds com Webpack, reduzindo o tamanho do bundle em cerca de 20–40% com code splitting e tree shaking",
				"Implementei interfaces pixel-perfect a partir do Figma e desenvolvi UI kits, acelerando o desenvolvimento em 20–30%",
				"Integrei APIs REST e WebSocket, garantindo funcionalidades em tempo real estáveis",
				"Gerenciei deploy e disponibilidade em VDS/VPS (Nginx, SSL), mantendo uptime de ~99%+",
				"Realizei refatoração e decomposição de componentes, reduzindo a complexidade e acelerando o desenvolvimento",
				"Participei de todo o ciclo de desenvolvimento, melhorando o time-to-market com estimativas mais precisas",
				"Mantive e evoluí bases de código em TypeScript, reduzindo erros em tempo de execução",
			],
			tags: [
				{ label: "Next.js", href: "https://nextjs.org/" },
				{ label: "React", href: "https://react.dev/" },
				{ label: "Webpack", href: "https://webpack.js.org/" },
				{ label: "Nginx", href: "https://nginx.org/" },
				{ label: "Redux Toolkit", href: "https://redux-toolkit.js.org/" },
			],
		},
		{
			date_start: new Date("2025-04-01"),
			date_end: new Date("2025-05-30"),
			company: "Sibcode",
			role: "Estagiário de Gerente de Projetos",
			location: "Tomsk, Remoto",
			description: [
				"Analisei a estrutura de produtos e formalizei requisitos por meio de briefs e especificações técnicas",
				"Modelei processos de negócio e fluxos de usuários (BPMN), melhorando a compreensão do produto antes do desenvolvimento",
				"Organizei o trabalho da equipe no Bitrix24: decomposição de tarefas, definição de prioridades e prazos, e acompanhamento com Kanban e gráfico de Gantt",
				"Desenvolvi soluções de UX/UI e criei protótipos no Figma com base em cenários de usuário",
				"Realizei testes funcionais, identificando erros críticos antes do lançamento e reduzindo problemas em produção",
			],
			tags: [
				{ label: "Sibcode", href: "https://sibcode.team/" },
				{ label: "Figma", href: "https://www.figma.com/" },
				{ label: "Miro", href: "https://miro.com/" },
				{ label: "Bitrix24", href: "https://www.bitrix24.com/" },
			],
		},
	],
};
